<a href="https://colab.research.google.com/github/S-Yatheesh/Course_Activities/blob/main/Numpy_Activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1.Create a NumPy array with values from 10 to 49 (inclusive).



In [ ]:
array = np.arange(10,50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])


● Reshape it into a 4x10 matrix.



In [ ]:
array = array.reshape(4,10)
array

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

● Then extract the last column from the reshaped matrix

In [ ]:
array[:,-1]

array([19, 29, 39, 49])

2 . Create two 3×3 matrices:

One filled with all 5s , One with values from 1 to 9

In [ ]:
matrix_1 = np.full((3,3),5)
print(f"First Matrix : \n",matrix_1)
matrix_2 = np.arange(1,10)
matrix_2 = matrix_2.reshape(3,3)
print(f"Second Matrix :\n",matrix_2)

First Matrix : 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
Second Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]



● Add the two matrices

In [ ]:
sum_of_matrix = np.add(matrix_1,matrix_2)
print(sum_of_matrix)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]



● Multiply them element-wise

In [ ]:
Product_of_matrix = np.multiply(matrix_1,matrix_2)
print(Product_of_matrix)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]



● Then find the transpose of the result


In [ ]:
Transpose = np.transpose(Product_of_matrix)
print(Transpose)

[[ 5 20 35]
 [10 25 40]
 [15 30 45]]


3.Create a NumPy array of 15 random integers between 10 and 100.

In [ ]:
arr_3 = np.random.randint(10, 101, 15)
print(arr_3)

[26 14 35 10 27 28 97 91 34 48 28 13 18 87 72]


● Replace all values greater than 50 with -1


In [ ]:
mask = arr_3 > 50
arr_3[mask] = -1

print("Modified array :", arr_3)

Modified array : [26 14 35 10 27 28 -1 -1 34 48 28 13 18 -1 -1]


● Count how many values were replaced.


In [ ]:
count = np.sum(mask)
print("Count of replaced values:", count)

Count of replaced values: 4



4.Generate a 5×4 array with random values between 0 and 1 (float).

In [ ]:
arr_4 = np.random.rand(5, 4)
arr_4

array([[0.99123939, 0.33581918, 0.60038909, 0.62077529],
       [0.73332406, 0.82169556, 0.61093317, 0.00905279],
       [0.31438718, 0.57185811, 0.82361008, 0.04362247],
       [0.17841588, 0.40704433, 0.17414692, 0.82071736],
       [0.48833059, 0.2391951 , 0.38968373, 0.7937249 ]])

● Find the row with the maximum sum of values.

In [ ]:
row_sums = arr_4.sum(axis=1)
max_row_index = np.argmax(row_sums)
print(f"The row with the maximum sum is:\n{arr_4[max_row_index]}")

The row with the maximum sum is:
[0.99123939 0.33581918 0.60038909 0.62077529]


● Normalize each row using the formula:

(x-min)/(max-min)

In [ ]:
normalized = (arr_4 - arr_4.min(axis=1, keepdims=True)) / (arr_4.max(axis=1, keepdims=True) - arr_4.min(axis=1, keepdims=True))
print("Normalized Array:\n", normalized)

Normalized Array:
 [[0.59719983 0.39555746 1.         0.        ]
 [0.12159904 1.         0.42314228 0.        ]
 [0.81340687 1.         0.         0.87452381]
 [0.68844038 0.22389484 1.         0.        ]
 [0.         0.51676293 0.46880081 1.        ]]


5.arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])

● Find all unique elements

● Find the duplicates (elements that appear more than once)


In [ ]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_elements = np.unique(arr)

vals, counts = np.unique(arr, return_counts=True)
duplicates = vals[counts > 1]

print("Unique:", unique_elements)
print("Duplicates:", duplicates)

Unique: [1 3 5 7 9]
Duplicates: [1 3 5]


6.Create a 6×6 NumPy array with values from 1 to 36.




In [ ]:
arr_6 = np.arange(1, 37).reshape(6, 6)
print(arr_6)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


● Extract the middle 4×4 submatrix.


In [ ]:
submatrix = arr_6[1:5, 1:5]
print("Submatrix:\n", submatrix)

Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]


● Then extract all even numbers from this submatrix.


In [ ]:
evens = submatrix[submatrix % 2 == 0]
print("Even numbers:", evens)

Even numbers: [ 8 10 14 16 20 22 26 28]


7.Generate an array of shape (3, 4) with values from 0 to 11.

In [ ]:
arr_7 = np.arange(12).reshape(3, 4)
print(arr_7)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


● Reshape it to (2, 6)


In [ ]:
arr_7 = arr_7.reshape(2, 6)
print(arr_7)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


● Then flatten it into a 1D array

In [ ]:
arr_7 = arr_7.flatten()
print(arr_7)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


● Convert the 1D array back to shape (4, 3)

In [ ]:
arr_7 = arr_7.reshape(4, 3)
print("Final shape (4,3):\n", arr_7)

Final shape (4,3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


8.Create an array: a = np.array([[1, 2], [3, 4]])



In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


● Append a new row [5, 6]


In [ ]:
a = np.vstack([a, [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


● Then append a new column [7, 8, 9]

In [ ]:
a = np.hstack([a, [[7], [8], [9]]])
print("Result:\n", a)

Result:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


9 .

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

c = np.array([7, 8, 9])

● Join them into a single array


In [ ]:
a, b, c = np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])
joined = np.concatenate([a, b, c])
print(joined)

[1 2 3 4 5 6 7 8 9]



● Reshape the result into a 3×3 matrix



In [ ]:
result = joined.reshape(3, 3)
print("Matrix:\n", result)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


● Extract the diagonal elements

In [ ]:
diagonal = np.diag(result)
print("Diagonal elements:", diagonal)

Diagonal elements: [1 5 9]


10.Create a NumPy array of integers from 1 to 20.

In [ ]:
arr_10 = np.arange(1, 21)
print(arr_10)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


● Extract all values that are divisible by 3 or 5.


In [ ]:
result_10 = arr_10[(arr_10 % 3 == 0) | (arr_10 % 5 == 0)]
print("Values:", result_10)

Values: [ 3  5  6  9 10 12 15 18 20]


● Count how many such values exist

In [ ]:
print("Count:", len(result_10))

Count: 9
